-- GO
-- CREATE TABLE registeredUsers
-- (
--     Username varchar(8) NOT NULL PRIMARY KEY,
--     FirstName varchar(255),
--     LastName varchar(255),
--     City varchar(255),
--     Country varchar(255),
--     Email VARCHAR(255),
--     UserPass varchar(10)
-- );
-- GO
-------------------------------------------------
-- GO 
--     SELECT * FROM Questions  
-- GO
------------------------------------------------- 
-- GO
-- CREATE TABLE Categories(
--     Category VARCHAR(255) NOT NULL,
--     FK_Username VARCHAR (8) NOT NULL FOREIGN KEY REFERENCES registeredUsers(Username) ,
--     CONSTRAINT PK_Categories PRIMARY KEY (Category,FK_Username)
-- );
-- GO
-------------------------------------------------
-- GO
-- CREATE TABLE Questions(
--     Question VARCHAR(255) NOT NULL,
--     Answer VARCHAR(255),
--     FK_Username VARCHAR (8) NOT NULL FOREIGN KEY REFERENCES registeredUsers(Username) ,
--     CONSTRAINT PK_Questions PRIMARY KEY (Question,FK_Username)
-- );
-- GO
------------------------------------------------
-- GO
-- INSERT INTO registeredUsers(Username,FirstName,LastName,
-- City,Country,Email,UserPass)
-- VALUES ('zoharavr','Zohar','Avraham',
-- 'New York','USA','zoharavr"post.bgu.ac.il','z123456');
-- GO
-------------------------------------------------
-- GO
-- CREATE TABLE Points(
--     ID int IDENTITY(1,1) PRIMARY KEY,
--     PointName VARCHAR(255) NOT NULL,
--     Category VARCHAR(255),
--     Views int,
--     Ratings real,
--     Ref VARCHAR (255)
-- );
-- GO
-- ----------------------------------------------------
-- GO
-- CREATE TABLE Comments(
--     FK_ID int  FOREIGN KEY REFERENCES Points(ID),
--     FK_Username VARCHAR (8) FOREIGN KEY REFERENCES registeredUsers(Username),
--     Comment VARCHAR(255) NOT NULL,
--     CONSTRAINT PK_Comments PRIMARY KEY (FK_ID,FK_Username)
-- );
-- GO
---------------------------------------------------
-- GO
-- INSERT INTO Points(PointName,Category,Views,Ratings)
-- VALUES ('Salt Meats Cheese‬','Food',0,0);
-- GO
-----------------------------------------------------
-- GO
-- CREATE TABLE Favorites(
--     FK_ID int  FOREIGN KEY REFERENCES Points(ID),
--     FK_Username VARCHAR (8) FOREIGN KEY REFERENCES registeredUsers(Username),
--     Added int IDENTITY(1,1),
--     CONSTRAINT PK_Favorites PRIMARY KEY (FK_ID,FK_Username)
-- );
-- GO
------------------------------------------------------
-- GO
-- ALTER TABLE Comments
-- ADD Date_Comment DATE;
-- GO
-- GO
-- SELECT TOP 2 * FROM Points INNER JOIN
-- (SELECT Category FROM Categories WHERE FK_Username='zoharavr') AS L ON L.Category=Points.Category
-- ORDER BY Points.Ratings DESC 
-- GO
GO
SELECT * FROM Questions
GO
GO
DELETE  FROM Comments
GO